//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileUpload()
        {
            this.PRs_FileUpload = new HashSet<PRs_FileUpload>();
            this.PurchaseRequisitions = new HashSet<PurchaseRequisition>();
        }
    
        public System.Guid uuid { get; set; }
        public int fileEntryId { get; set; }
        public int uploadUserId { get; set; }
        public System.DateTime uploadDate { get; set; }
        public string FileName { get; set; }
        public string FullPath { get; set; }
        public string description { get; set; }
        public string Extension { get; set; }
        public byte[] File { get; set; }
        public Nullable<bool> archivedFlag { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRs_FileUpload> PRs_FileUpload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseRequisition> PurchaseRequisitions { get; set; }
    }
}
