//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTask
    {
        public System.Guid uuid { get; set; }
        public string jobNo { get; set; }
        public string jobTaskNo { get; set; }
        public int custId { get; set; }
    }
}
