//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUB_Malaysia_Berhad_Vendor
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Name { get; set; }
        public string Search_Name { get; set; }
        public string Name_2 { get; set; }
        public string Address { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string Phone_No_ { get; set; }
        public string Telex_No_ { get; set; }
        public string Our_Account_No_ { get; set; }
        public string Territory_Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public decimal Budgeted_Amount { get; set; }
        public string Vendor_Posting_Group { get; set; }
        public string Currency_Code { get; set; }
        public string Language_Code { get; set; }
        public int Statistics_Group { get; set; }
        public string Payment_Terms_Code { get; set; }
        public string Fin__Charge_Terms_Code { get; set; }
        public string Purchaser_Code { get; set; }
        public string Shipment_Method_Code { get; set; }
        public string Shipping_Agent_Code { get; set; }
        public string Invoice_Disc__Code { get; set; }
        public string Country_Region_Code { get; set; }
        public int Blocked { get; set; }
        public string Pay_to_Vendor_No_ { get; set; }
        public int Priority { get; set; }
        public string Payment_Method_Code { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public int Application_Method { get; set; }
        public byte Prices_Including_VAT { get; set; }
        public string Fax_No_ { get; set; }
        public string Telex_Answer_Back { get; set; }
        public string VAT_Registration_No_ { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public byte[] Picture { get; set; }
        public string GLN { get; set; }
        public string Post_Code { get; set; }
        public string County { get; set; }
        public string E_Mail { get; set; }
        public string Home_Page { get; set; }
        public string No__Series { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public byte Block_Payment_Tolerance { get; set; }
        public string IC_Partner_Code { get; set; }
        public decimal Prepayment__ { get; set; }
        public int Partner_Type { get; set; }
        public System.Guid Image { get; set; }
        public string Creditor_No_ { get; set; }
        public string Preferred_Bank_Account_Code { get; set; }
        public string Cash_Flow_Payment_Terms_Code { get; set; }
        public string Primary_Contact_No_ { get; set; }
        public string Responsibility_Center { get; set; }
        public string Location_Code { get; set; }
        public string Lead_Time_Calculation { get; set; }
        public string Base_Calendar_Code { get; set; }
        public string Document_Sending_Profile { get; set; }
        public string Address_3 { get; set; }
        public string Business_Registration_No_ { get; set; }
        public string RMCD_Approval_No_ { get; set; }
        public string Self_Billed_Prefix { get; set; }
        public string Self_Billed_Last_Used_No_ { get; set; }
        public byte Non_GST_Registrant_BK { get; set; }
        public int GST_Registrant_Type { get; set; }
        public string FRS_Approval_No_ { get; set; }
        public string WHT_Business_Posting_Group { get; set; }
        public string WHT_Registration_ID { get; set; }
        public string ID_No_ { get; set; }
        public string ID_Type { get; set; }
        public string Identification_No_ { get; set; }
        public string EFT_EmailNotification { get; set; }
        public string Resident_Status { get; set; }
        public string EFT_EmailNotification2 { get; set; }
        public string EFT_EmailNotification3 { get; set; }
        public string EFT_EmailNotification4 { get; set; }
        public string EFT_EmailNotification5 { get; set; }
        public string EFT_EmailNotification6 { get; set; }
        public string EFT_EmailNotification7 { get; set; }
        public string EFT_EmailNotification8 { get; set; }
        public string EFT_EmailNotification9 { get; set; }
        public string EFT_EmailNotification10 { get; set; }
        public string BeneficiaryName1 { get; set; }
        public string BeneficiaryName2 { get; set; }
        public string BeneficiaryName3 { get; set; }
    }
}
