//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUB_Malaysia_Berhad_Fixed_Asset
    {
        public byte[] timestamp { get; set; }
        public string No_ { get; set; }
        public string Description { get; set; }
        public string Search_Description { get; set; }
        public string Description_2 { get; set; }
        public string FA_Class_Code { get; set; }
        public string FA_Subclass_Code { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public string Global_Dimension_2_Code { get; set; }
        public string Location_Code { get; set; }
        public string FA_Location_Code { get; set; }
        public string Vendor_No_ { get; set; }
        public int Main_Asset_Component { get; set; }
        public string Component_of_Main_Asset { get; set; }
        public byte Budgeted_Asset { get; set; }
        public System.DateTime Warranty_Date { get; set; }
        public string Responsible_Employee { get; set; }
        public string Serial_No_ { get; set; }
        public System.DateTime Last_Date_Modified { get; set; }
        public byte Blocked { get; set; }
        public byte[] Picture { get; set; }
        public string Maintenance_Vendor_No_ { get; set; }
        public byte Under_Maintenance { get; set; }
        public System.DateTime Next_Service_Date { get; set; }
        public byte Inactive { get; set; }
        public string No__Series { get; set; }
        public string FA_Posting_Group { get; set; }
        public System.Guid Image { get; set; }
        public byte FA_Tag_No__Printed { get; set; }
        public string WHT_Product_Posting_Group { get; set; }
        public string Shortcut_Dimension_3_Code { get; set; }
        public string Shortcut_Dimension_4_Code { get; set; }
        public string Shortcut_Dimension_5_Code { get; set; }
        public string Shortcut_Dimension_6_Code { get; set; }
        public byte Batch_Write_Off { get; set; }
        public System.DateTime Acq_Posting_Date { get; set; }
        public byte Disposed { get; set; }
        public decimal FA_Write_Off_Qty { get; set; }
        public byte For_Disposal { get; set; }
        public byte DirectWriteOff { get; set; }
        public decimal FA_Transfer_Qty { get; set; }
        public string New_Shortcut_Dimension_1_Code { get; set; }
        public string New_Shortcut_Dimension_2_Code { get; set; }
        public string New_Shortcut_Dimension_3_Code { get; set; }
        public string New_Shortcut_Dimension_4_Code { get; set; }
        public string New_FA_Location { get; set; }
        public string FA_Tag_No { get; set; }
        public string Shortcut_Dimension_7_Code { get; set; }
        public string Shortcut_Dimension_8_Code { get; set; }
        public string New_Shortcut_Dimension_5_Code { get; set; }
        public string New_Shortcut_Dimension_6_Code { get; set; }
        public string New_Shortcut_Dimension_7_Code { get; set; }
        public string New_Shortcut_Dimension_8_Code { get; set; }
        public byte CGA { get; set; }
        public int No__of_CGA_Interval { get; set; }
        public byte CGA_is_Calculated { get; set; }
        public byte CGA_Rate_is_Applied { get; set; }
        public System.DateTime Acquistion_Date { get; set; }
        public byte CGA_Adjustment_Posted { get; set; }
        public System.DateTime First_Interval_End_Date { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public byte PE_is_Calculated { get; set; }
    }
}
