//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUB_TelEntities : DbContext
    {
        public KUB_TelEntities()
            : base("name=KUB_TelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KUB_Telekomunikasi_Sdn_Bhd_Contact> KUB_Telekomunikasi_Sdn_Bhd_Contact { get; set; }
        public virtual DbSet<KUB_Telekomunikasi_Sdn_Bhd_Item> KUB_Telekomunikasi_Sdn_Bhd_Item { get; set; }
        public virtual DbSet<KUB_Telekomunikasi_Sdn_Bhd_Vendor> KUB_Telekomunikasi_Sdn_Bhd_Vendor { get; set; }
    }
}
