//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUBMEntities : DbContext
    {
        public KUBMEntities()
            : base("name=KUBMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KUB_Malaysia_Berhad_Contact> KUB_Malaysia_Berhad_Contact { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Contact_Business_Relation> KUB_Malaysia_Berhad_Contact_Business_Relation { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Dimension_Value> KUB_Malaysia_Berhad_Dimension_Value { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Fixed_Asset> KUB_Malaysia_Berhad_Fixed_Asset { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_G_L_Account> KUB_Malaysia_Berhad_G_L_Account { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Item> KUB_Malaysia_Berhad_Item { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Job> KUB_Malaysia_Berhad_Job { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Job_Task> KUB_Malaysia_Berhad_Job_Task { get; set; }
        public virtual DbSet<KUB_Malaysia_Berhad_Vendor> KUB_Malaysia_Berhad_Vendor { get; set; }
    }
}
