//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public System.Guid uuid { get; set; }
        public int locationId { get; set; }
        public string locationCode { get; set; }
        public string locationName { get; set; }
        public string locationAddress { get; set; }
        public string locationCity { get; set; }
        public string PostCode { get; set; }
        public string State { get; set; }
        public string CountryRegionCode { get; set; }
        public int custId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
