//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageList
    {
        public Nullable<int> fromUserId { get; set; }
        public string FromUserName { get; set; }
        public int msgId { get; set; }
        public System.DateTime msgDate { get; set; }
        public Nullable<int> PRId { get; set; }
        public string PRNo { get; set; }
        public string message { get; set; }
        public string msgType { get; set; }
        public Nullable<int> toUserId { get; set; }
        public string ToUserName { get; set; }
    }
}
