//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMsg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationMsg()
        {
            this.NotiGroups = new HashSet<NotiGroup>();
        }
    
        public System.Guid uuid { get; set; }
        public int msgId { get; set; }
        public string message { get; set; }
        public Nullable<int> PRId { get; set; }
        public Nullable<int> POId { get; set; }
        public Nullable<int> fromUserId { get; set; }
        public System.DateTime msgDate { get; set; }
        public string msgType { get; set; }
        public Nullable<bool> done { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotiGroup> NotiGroups { get; set; }
    }
}
