//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotiGroup
    {
        public System.Guid uuid { get; set; }
        public int msgId { get; set; }
        public int toUserId { get; set; }
        public Nullable<bool> resubmit { get; set; }
    
        public virtual NotificationMsg NotificationMsg { get; set; }
        public virtual User User { get; set; }
    }
}
