//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PONoEditHistory
    {
        public System.Guid uuid { get; set; }
        public int POId { get; set; }
        public System.DateTime lastPODate { get; set; }
        public string lastPONo { get; set; }
        public string newPONo { get; set; }
        public int modifiedByUserId { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public int custId { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
