//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRs_FileUpload
    {
        public System.Guid uuid { get; set; }
        public int fileEntryId { get; set; }
        public int PRId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual FileUpload FileUpload { get; set; }
        public virtual Project Project { get; set; }
        public virtual PurchaseRequisition PurchaseRequisition { get; set; }
    }
}
