//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KUBOnlinePRPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.PO_Item = new HashSet<PO_Item>();
            this.PONoEditHistories = new HashSet<PONoEditHistory>();
        }
    
        public System.Guid uuid { get; set; }
        public int POId { get; set; }
        public Nullable<int> PRId { get; set; }
        public string PONo { get; set; }
        public int CustId { get; set; }
        public System.DateTime PODate { get; set; }
        public int projectId { get; set; }
        public int vendorId { get; set; }
        public string VendorQuoteNo { get; set; }
        public Nullable<int> vendorStaffId { get; set; }
        public int Saved { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public Nullable<int> PreparedById { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public bool Submited { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public int POAging { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public int Discount_ { get; set; }
        public Nullable<decimal> TotalExcSST { get; set; }
        public Nullable<decimal> TotalSST { get; set; }
        public Nullable<decimal> TotalIncSST { get; set; }
        public string SpecsReviewerId { get; set; }
        public Nullable<int> PayToVendorId { get; set; }
        public Nullable<int> PaymentTermsId { get; set; }
        public Nullable<int> LocationCodeId { get; set; }
        public Nullable<int> PurchaserId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string StatusId { get; set; }
    
        public virtual PaymentTerm PaymentTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Item> PO_Item { get; set; }
        public virtual POStatu POStatu { get; set; }
        public virtual Project Project { get; set; }
        public virtual Purchaser Purchaser { get; set; }
        public virtual PurchaseRequisition PurchaseRequisition { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual VendorStaff VendorStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PONoEditHistory> PONoEditHistories { get; set; }
    }
}
